### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by benblack86** [strongriley/remove-tumblr-redirects#1]
Hi, can you provide some examples of links that don't work? Thanks.

**Comment by strongriley** [comment]
Sure! This didn't work:
https://overcast.fm/+BP58gdytI

The + gets translated wrong.

**Comment by benblack86** [comment]
Hopefully have a fix by end of next week :)

**Comment by benblack86** [comment]
The fix it out. Your links shouldn't get broken now.

**Comment by strongriley** [comment]
Thanks Ben!
